[versions]
pluginYml = "0.8.0"
paperApi = "1.21.10-R0.1-SNAPSHOT"
customItems = "1.0-SNAPSHOT"
griefPrevention = "17.0.0"
messagesHelper = "1.1-SNAPSHOT"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
griefPrevention = { group = "com.github.TechFortress", name = "GriefPrevention", version.ref  = "griefPrevention" }
customItems = { group = "uk.co.notnull", name = "CustomItemsAPI", version.ref  = "customItems" }
messagesHelper = { group = "uk.co.notnull", name= "MessagesHelper-paper", version.ref = "messagesHelper" }

[plugins]
pluginYml = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYml" }
